ALTER TABLE #__alvearium_blooms ADD `type` INT(1) NOT NULL DEFAULT '1';

CREATE TABLE `#__alvearium_dates` (
	`id` INT NOT NULL AUTO_INCREMENT,
	`title` MEDIUMTEXT NOT NULL DEFAULT '',
	`rep` BOOLEAN NOT NULL DEFAULT '0',
	`notes` LONGTEXT NOT NULL,
	`state` TINYINT(3) NOT NULL DEFAULT '0',
	`created` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
	`created_by` INT(10) NOT NULL DEFAULT '0',
	`catid` INT(10) NOT NULL DEFAULT '0',
	PRIMARY KEY (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=0 DEFAULT CHARSET=utf8;
